/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.52
 * Generated at: 2020-06-18 19:07:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class korEdu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title> 동국대학교 Dbroad </title>\r\n");
      out.write("<!-- 파비콘  -->\r\n");
      out.write("<link type=\"img/x-icon\" rel=\"icon\" href=\"http://blogfiles.naver.net/20140310_181/rokpia0071_1394439345125aKwKu_PNG/%B5%BF%B1%B9%B4%EB%C7%D0%B1%B3-%B7%CE%B0%ED.png\">\r\n");
      out.write("<!-- 파비콘  -->\r\n");
      out.write("\r\n");
      out.write("<!-- style -->\r\n");
      out.write("<style>\r\n");
      out.write("\tdiv {\r\n");
      out.write("    display: block;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\theader{ /* 헤더 */\r\n");
      out.write("\tmargin: 30px;\r\n");
      out.write("\twidth: auto;\r\n");
      out.write("\theight: 53px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#logo{ /*헤더로고*/\r\n");
      out.write("\twidth: 350px;\r\n");
      out.write("\theight: 50px;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("        left: 15px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\th3 { /*헤더 nav*/\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("        right: 85px;\r\n");
      out.write("        bottom: 70px;\r\n");
      out.write("\ttext-align: right;\r\n");
      out.write("\tcolor: #a5a5a5; /* 짙은 회색 */ \r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tsection{ /*이미지*/\r\n");
      out.write("\tmargin: 500px;\r\n");
      out.write("\tmargin-top:0px;\r\n");
      out.write("\tmargin-bottom:50px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tbody {\r\n");
      out.write("    height: auto;\r\n");
      out.write("    font-size: .90em;\r\n");
      out.write("    position: relative;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\thtml, body {\r\n");
      out.write("    height: 100%;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("    font-family: 'NanumGothic';\r\n");
      out.write("    line-height: 1.5;\r\n");
      out.write("    color: #090909;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfooter {\r\n");
      out.write("\tbackground-color: #333333; /* 배경 진한 회색 */\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    padding: 25px 0 38px 0;\r\n");
      out.write("    color: #cecece;\t\t\t   /* 글자 밝은 회색 */\r\n");
      out.write("    border-top: 3px solid #2f2f2f;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#footerSpan {\r\n");
      out.write("\tcolor :#F79350; /*주황*/\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\taddress{\r\n");
      out.write("\tfont-style:unset; /* 기울기X */\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("</style>\r\n");
      out.write("<!-- style -->\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- header -->\t\r\n");
      out.write("<header>\r\n");
      out.write("\t<h1>\r\n");
      out.write("\t\t&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t<a href=\"main.jsp\" title=\"동국대학교 경주캠퍼스 Dbroad\">\r\n");
      out.write("\t\t\t<img id=\"logo\" \r\n");
      out.write("\t\t\tsrc=\"image/Dlogo.JPG\">\r\n");
      out.write("\t\t</a>\t\r\n");
      out.write("\t</h1>\r\n");
      out.write("\t<h3>Hangul education&nbsp;&nbsp;&nbsp;&nbsp;|\r\n");
      out.write("\t&nbsp;&nbsp;&nbsp;&nbsp;ハングル きょうい &nbsp;&nbsp;&nbsp;&nbsp;| <!-- 일본어 -->\r\n");
      out.write("\t&nbsp;&nbsp;&nbsp;&nbsp;韩文 敎育 &nbsp;&nbsp;&nbsp;&nbsp;|\t\t <!-- 중국어 -->\r\n");
      out.write("\t&nbsp;&nbsp;&nbsp;&nbsp;chữ Hàn Quốc sự giáo dục</h3>\t\t\t <!-- 베트남 -->\r\n");
      out.write("</header>\t\r\n");
      out.write("<!-- header -->\t\r\n");
      out.write("\r\n");
      out.write("<!-- section -->\r\n");
      out.write("<section>\r\n");
      out.write("<a href=\"https://www.cakec.com/teachingnlearning\r\n");
      out.write("\">\r\n");
      out.write("  \t<img src=\"image/캐나다.JPG\" style=\"width:100%\"> <!-- 캐나다 -->\r\n");
      out.write(" </a>\r\n");
      out.write("<br><br> \r\n");
      out.write(" <a href=\"http://www.kankoku.or.kr/smain.html\">\r\n");
      out.write("  \t<img src=\"image/일본.JPG\" style=\"width:100%\"> <!-- 일본 -->\r\n");
      out.write(" </a>\r\n");
      out.write("<br><br> \r\n");
      out.write(" <a href=\"http://www.klech.org/\">\r\n");
      out.write("  \t<img src=\"image/베트남.JPG\" style=\"width:100%\"> <!-- 베트남 -->\r\n");
      out.write(" </a>\r\n");
      out.write("<br><br> \r\n");
      out.write(" <a href=\"https://www.chicagokec.org/\">\r\n");
      out.write("  \t<img src=\"image/미국시카고.JPG\" style=\"width:100%\"> <!-- 미국 -->\r\n");
      out.write(" </a>\r\n");
      out.write("<br><br> \r\n");
      out.write(" <a href=\"http://www.educoree.fr/\">\r\n");
      out.write("  \t<img src=\"image/프랑스.JPG\" style=\"width:100%\"> <!-- 프랑스 -->\r\n");
      out.write(" </a>\r\n");
      out.write("<br><br> \r\n");
      out.write(" <a href=\"http://changesoul.de/keid/board.php?board=keidbmain&command=skin_insert&exe=insert_iboard1_home\">\r\n");
      out.write("  \t<img src=\"image/독일.JPG\" style=\"width:100%\"> <!-- 독일 -->\r\n");
      out.write(" </a>\r\n");
      out.write("<br><br> \r\n");
      out.write(" <a href=\"http://www.koreaneducentreinuk.org/\">\r\n");
      out.write("  \t<img src=\"image/영국.JPG\" style=\"width:100%\"> <!-- 영국 -->\r\n");
      out.write(" </a>\r\n");
      out.write("<br><br> \r\n");
      out.write(" <a href=\"http://www.ieka.net/\">\r\n");
      out.write("  \t<img src=\"image/아르헨티나.JPG\" style=\"width:100%\"> <!-- 아르헨티나 -->\r\n");
      out.write(" </a>\r\n");
      out.write("<br><br> \r\n");
      out.write(" <a href=\"http://www.auskec.kr/\">\r\n");
      out.write("  \t<img src=\"image/호주시드니.JPG\" style=\"width:100%\"> <!-- 호주 -->\r\n");
      out.write(" </a>\r\n");
      out.write("<br><br> \r\n");
      out.write(" <a href=\"http://www.vladikoredu.kr/main/main.php\">\r\n");
      out.write("  \t<img src=\"image/러시아블라디보스톡.JPG\" style=\"width:100%\"> <!-- 러시아 -->\r\n");
      out.write(" </a>\r\n");
      out.write("<br><br> \r\n");
      out.write(" <a href=\"https://tashkec.uz/ko/\">\r\n");
      out.write("  \t<img src=\"image/우즈벡.JPG\" style=\"width:100%\"> <!-- 우즈벡 -->\r\n");
      out.write(" </a>\r\n");
      out.write("<br><br> \r\n");
      out.write(" <a href=\"http://www.koreacenter.kz/\">\r\n");
      out.write("  \t<img src=\"image/카자흐스탄.JPG\" style=\"width:100%\"> <!-- 카자흐스탄 -->\r\n");
      out.write(" </a>\r\n");
      out.write("<br><br> \r\n");
      out.write(" <a href=\"https://www.edubis.kg/\">\r\n");
      out.write("  \t<img src=\"image/키르기스스탄.JPG\" style=\"width:100%\"> <!-- 키르기스스탄 -->\r\n");
      out.write(" </a>\r\n");
      out.write(" \r\n");
      out.write("</section>\r\n");
      out.write("<!-- section -->\r\n");
      out.write("\r\n");
      out.write("<!-- footer -->\t\r\n");
      out.write("<footer> \r\n");
      out.write("\t<address>[38066]  경상북도 경주시 동대로 123 동국대학교 경주캠퍼스 \r\n");
      out.write("\t\t<span>&nbsp;&nbsp;T.054-770-2114 &nbsp;&nbsp;F.054-770-2001</span>\r\n");
      out.write("\t</address>\r\n");
      out.write("\t<p>COPYRIGHT ⓒ&nbsp;&nbsp;<span id=\"footerSpan\">DONGGUK UNIVERSITY \r\n");
      out.write("\t   GYEONGJU</span>&nbsp;&nbsp;COMPUTER ENGINEERING 20 Lee gyuwon.\r\n");
      out.write("\t</p>\t\r\n");
      out.write("</footer>\r\n");
      out.write("<!-- footer -->\t\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
