/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.52
 * Generated at: 2020-06-14 19:52:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class NewFile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("/* 硫��� �щ�쇱�대�� Slideshow container */\r\n");
      out.write("\r\n");
      out.write("/* Slideshow container */\r\n");
      out.write("\r\n");
      out.write("* {box-sizing:border-box}\r\n");
      out.write("\r\n");
      out.write("body {font-family: Verdana,sans-serif;margin:0}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/* Slideshow container */\r\n");
      out.write("\r\n");
      out.write(".slideshow-container {\r\n");
      out.write("\r\n");
      out.write("width: 100%;\r\n");
      out.write("\r\n");
      out.write("height: 300px;\r\n");
      out.write("\r\n");
      out.write("position: static;\r\n");
      out.write("\r\n");
      out.write("margin: auto;\r\n");
      out.write("\r\n");
      out.write("margin-top: 50px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".main_slideImg{\r\n");
      out.write("\r\n");
      out.write("width: 100%; \r\n");
      out.write("\r\n");
      out.write("height: 300px; \r\n");
      out.write("\r\n");
      out.write("top : 100px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/* Next & previous buttons */\r\n");
      out.write("\r\n");
      out.write(".prev, .next {\r\n");
      out.write("\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("\r\n");
      out.write("  position: absolute;\r\n");
      out.write("\r\n");
      out.write("  text-align : center;\r\n");
      out.write("\r\n");
      out.write("  top: 0;\r\n");
      out.write("\r\n");
      out.write("  top: 20%;\r\n");
      out.write("\r\n");
      out.write("  width: 3%;\r\n");
      out.write("\r\n");
      out.write("  padding: 16px;\r\n");
      out.write("\r\n");
      out.write("  margin-top: -22px;\r\n");
      out.write("\r\n");
      out.write("  color: white;\r\n");
      out.write("\r\n");
      out.write("  font-weight: bold;\r\n");
      out.write("\r\n");
      out.write("  font-size: 18px;\r\n");
      out.write("\r\n");
      out.write("  transition: 0.6s ease;\r\n");
      out.write("\r\n");
      out.write("  border-radius: 0 3px 3px 0;\r\n");
      out.write("\r\n");
      out.write("  z-index: 100;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/* Position the \"next button\" to the right */\r\n");
      out.write("\r\n");
      out.write(".next {\r\n");
      out.write("\r\n");
      out.write("  right: 0;\r\n");
      out.write("\r\n");
      out.write("  border-radius: 3px 0 0 3px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/* On hover, add a black background color with a little bit see-through */\r\n");
      out.write("\r\n");
      out.write(".prev:hover, .next:hover {\r\n");
      out.write("\r\n");
      out.write("  background-color: rgba(0,0,0,0.8);\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/* Caption text */\r\n");
      out.write("\r\n");
      out.write(".text {\r\n");
      out.write("\r\n");
      out.write("  color: #f2f2f2;\r\n");
      out.write("\r\n");
      out.write("  font-size: 15px;\r\n");
      out.write("\r\n");
      out.write("  padding: 8px 12px;\r\n");
      out.write("\r\n");
      out.write("  position: absolute;\r\n");
      out.write("\r\n");
      out.write("  bottom: 8px;\r\n");
      out.write("\r\n");
      out.write("  width: 100%;\r\n");
      out.write("\r\n");
      out.write("  text-align: center;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/* Number text (1/3 etc) */\r\n");
      out.write("\r\n");
      out.write(".numbertext {\r\n");
      out.write("\r\n");
      out.write("  color: #f2f2f2;\r\n");
      out.write("\r\n");
      out.write("  font-size: 12px;\r\n");
      out.write("\r\n");
      out.write("  padding: 8px 12px;\r\n");
      out.write("\r\n");
      out.write("  position: absolute;\r\n");
      out.write("\r\n");
      out.write("  top: 0;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/* The dots/bullets/indicators */\r\n");
      out.write("\r\n");
      out.write(".dot {\r\n");
      out.write("\r\n");
      out.write("  cursor:pointer;\r\n");
      out.write("\r\n");
      out.write("  height: 13px;\r\n");
      out.write("\r\n");
      out.write("  width: 13px;\r\n");
      out.write("\r\n");
      out.write("  margin: 0 2px;\r\n");
      out.write("\r\n");
      out.write("  background-color: #bbb;\r\n");
      out.write("\r\n");
      out.write("  border-radius: 50%;\r\n");
      out.write("\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("\r\n");
      out.write("  transition: background-color 0.6s ease;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".active, .dot:hover {\r\n");
      out.write("\r\n");
      out.write("  background-color: #717171;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/* Fading animation */\r\n");
      out.write("\r\n");
      out.write(".fade2 {\r\n");
      out.write("\r\n");
      out.write("  -webkit-animation-name: fade;\r\n");
      out.write("\r\n");
      out.write("  -webkit-animation-duration: 0.5s;\r\n");
      out.write("\r\n");
      out.write("  animation-name: fade;\r\n");
      out.write("\r\n");
      out.write("  animation-duration: 5s;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("@-webkit-keyframes fade2 {\r\n");
      out.write("\r\n");
      out.write("  from {opacity: .4}\r\n");
      out.write("\r\n");
      out.write("  to {opacity: 1}\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("@keyframes fade2 {\r\n");
      out.write("\r\n");
      out.write("  from {opacity: .4}\r\n");
      out.write("\r\n");
      out.write("  to {opacity: 1}\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/* On smaller screens, decrease text size */\r\n");
      out.write("\r\n");
      out.write("@media only screen and (max-width: 300px) {\r\n");
      out.write("\r\n");
      out.write("  .slprev, .slnext,.text {font-size: 11px}\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<!-- 硫��� �щ�쇱�대�� -->\r\n");
      out.write("<div class=\"slideshow-container\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"mySlides fade2\">\r\n");
      out.write("\r\n");
      out.write("<img class=\"main_slideImg\" src=\"image/��援�a.jpg\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"mySlides fade2\">\r\n");
      out.write("\r\n");
      out.write("<img class=\"main_slideImg\" src=\"image/�몄�����a.jpg\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"mySlides fade2\">\r\n");
      out.write("\r\n");
      out.write("<img class=\"main_slideImg\" src=\"image/��蹂�a.jpg\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<a class=\"prev\" onclick=\"plusSlides(-1)\">��</a>\r\n");
      out.write("\r\n");
      out.write("<a class=\"next\"onclick=\"plusSlides(1)\">��</a>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div style=\"text-align: center\">\r\n");
      out.write("\r\n");
      out.write("<span class=\"dot\" onclick=\"currentSlide(1)\"></span> \r\n");
      out.write("\r\n");
      out.write("<span class=\"dot\" onclick=\"currentSlide(2)\"></span>\r\n");
      out.write("\r\n");
      out.write("<span class=\"dot\" onclick=\"currentSlide(3)\"></span>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("//�щ�쇱�대�� �ㅽ�щ┰\r\n");
      out.write("\r\n");
      out.write("var slideIndex = 1;\r\n");
      out.write("\r\n");
      out.write("showSlides(slideIndex);\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function plusSlides(n) {\r\n");
      out.write("\r\n");
      out.write("  showSlides(slideIndex += n);\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function currentSlide(n) {\r\n");
      out.write("\r\n");
      out.write("  showSlides(slideIndex = n);\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function showSlides(n) {\r\n");
      out.write("\r\n");
      out.write("  var i;\r\n");
      out.write("\r\n");
      out.write("  var slides = document.getElementsByClassName(\"mySlides\");\r\n");
      out.write("\r\n");
      out.write("  var dots = document.getElementsByClassName(\"dot\");\r\n");
      out.write("\r\n");
      out.write("  if (n > slides.length) {slideIndex = 1}\r\n");
      out.write("\r\n");
      out.write("  if (n < 1) {slideIndex = slides.length}\r\n");
      out.write("\r\n");
      out.write("  for (i = 0; i < slides.length; i++) {\r\n");
      out.write("\r\n");
      out.write("      slides[i].style.display = \"none\";\r\n");
      out.write("\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  for (i = 0; i < dots.length; i++) {\r\n");
      out.write("\r\n");
      out.write("      dots[i].className = dots[i].className.replace(\" active\", \"\");\r\n");
      out.write("\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  slides[slideIndex-1].style.display = \"block\";\r\n");
      out.write("\r\n");
      out.write("  dots[slideIndex-1].className += \" active\";\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
